### PR TITLE
gulp/jade/stylus/es6 refactor

### PR DESCRIPTION
**Pull request by johnazre**

### CODE REVIEW

**Comment by Glathrop** [comment]
@johnazre before I delete this branch.... is this gulp setup supposed to kickoff our server after we perform install isntructions? I'm having issues and want to make sure I understand setup.

**Comment by johnazre** [comment]
Yes. All you need to do is npm install and use "gulp" on the command line after the npm install is done.

**Comment by johnazre** [comment]
@Glathrop

**Comment by johnazre** [comment]
What is it saying?

**Pull request merged**
